webtalk_init -webtalk_dir C:/Users/zacht/Documents/- School/COEN 4710 - Computer Hardware/Projects/Project 2/project_2c/project_2c.sim/sim_1/behav/xsim/xsim.dir/RISCV_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  8 00:33:39 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "512f67c6-aed1-47e5-80e3-85bc78c7401a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "07e380d6dd0649ccbb9eabdbcc102dee" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 4900HS with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3548042379 -regid "" -xml C:/Users/zacht/Documents/- School/COEN 4710 - Computer Hardware/Projects/Project 2/project_2c/project_2c.sim/sim_1/behav/xsim/xsim.dir/RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/zacht/Documents/- School/COEN 4710 - Computer Hardware/Projects/Project 2/project_2c/project_2c.sim/sim_1/behav/xsim/xsim.dir/RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/zacht/Documents/- School/COEN 4710 - Computer Hardware/Projects/Project 2/project_2c/project_2c.sim/sim_1/behav/xsim/xsim.dir/RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
